version: '3.1'



volumes:
  nodered:

services:

  mqtt_broker:
    image: mqtt_broker
    build: ./mqtt_broker/
    networks:
      - webnet
    volumes:
      - ./mqtt_broker/mosquitto/config:/mosquitto/config
      - ./mqtt_broker/mosquitto/data:/mosquitto/data
      - ./mqtt_broker/mosquitto/log:/mosquitto/log
      - /etc/localtime:/etc/localtime:ro
    restart: on-failure

  nodered:
    depends_on:
        - mqtt_broker
    image: nodered
    build: ./nodered
    volumes:
      - nodered:/data 
    ports:
      - "1880:1880"
      - "1999:1999"
      - "2000:2000"
    networks: 
      - webnet
    restart: on-failure


  # aws_mqtt_connector:
  #   depends_on:
  #     - mqtt_broker
  #   image: aws_mqtt_connector
  #   build: ./aws_mqtt_connector/
  #   volumes:
  #     - ./aws_mqtt_connector/data:/data
  #   networks:
  #     - webnet
  #   restart: on-failure

  # balluff_master_connector:
  #   depends_on:
  #     - mqtt_broker
  #   image: balluff_master_connector
  #   build: ./balluff_master_connector/
  #   environment:
  #     - MASTER_IP
  #     - QUEUE_DICT
  #   networks:
  #     - webnet
  #   restart: on-failure
  
networks:
  webnet:
    driver: bridge






