version: '3.1'
services:
  mqtt_broker:
    image: mqtt_broker
    build: ./mqtt_broker/
    networks:
      - webnet
    volumes:
      - ./mqtt_broker/mosquitto/config:/mosquitto/config
      - ./mqtt_broker/mosquitto/data:/mosquitto/data
      - ./mqtt_broker/mosquitto/log:/mosquitto/log
      - /etc/localtime:/etc/localtime:ro
    restart: on-failure

  nodered:
    depends_on:
        - mqtt_broker
    image: nodered
    build: ./nodered
    volumes:
      - nodered:/data 
    ports:
      - "1880:1880"
      - "1999:1999/udp"
      - "2000:2000/udp"
    networks: 
      - default
      - webnet
    restart: on-failure

  influxdb:
    image: influxdb:latest
    ports:
      - '8086:8086'
    restart: on-failure

networks:
  webnet:
    driver: bridge
  default:
volumes:
    nodered:
    






